---
title: 'Lab XX'
output:
  html_document:
    theme: readable
    df_print: paged
    highlight: tango
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F, fig.align='center', fig.width=9 )
```

```{css, echo=F}
p {
color: black;
margin: 0 0 20px 0;
}

td {
    padding: 3px 10px 3px 10px;
    text-align: center;
}

table
{ 
    margin-left: auto;
    margin-right: auto;
    margin-top:80px;
    margin-bottom:100px;
}

h1, h2{
  margin-top:100px;
  margin-bottom:20px;
}

H5{
    text-align: center;
    color: gray;
    font-size:0.8em;
}

img {
    max-width: 90%;
    display: block;
    margin-right: auto;
    margin-left: auto;
    margin-top:30px;
    margin-bottom:20px;
}
```


```{r, echo=F}
library( dplyr )
library( pander )

URL <- "https://github.com/DS4PS/Data-Science-Class/blob/master/DATA/TempeTrafficAccidents.rds?raw=true"
dat <- readRDS(gzcon(url( URL )))
```




# Diff-N-Diff Models

```{r}
T1 <- 55
T2 <- 85
CF <- 75
C1 <- 75
C2 <- 95

palette( c( adjustcolor( "steelblue", alpha.f=1), adjustcolor( "darkred", alpha.f=1)  ) )

plot( c(0,1,0,1), c(T1,T2,C1,C2), bty="n",
      xlim=c(-0.5,2), ylim=c(50,100),
      col=c(1,1,2,2), pch=19, cex=6, 
      xaxt="n", yaxt="n",
      xlab="", ylab="", main="Performance on Exam Measuring Proficiency in Arithmetic" )



segments( x0=0, x1=1, y0=C1, y1=C2, col=2, lwd=2 )
segments( x0=0, x1=1, y0=T1, y1=T2, col=1, lwd=2 )

text( c(0,1,0,1), c(T1,T2,C1,C2), c(T1,T2,C1,C2), cex=1.5, col="white" )

axis( side=1, at=c(0,1), 
      labels=c("End of 2nd Grade",
      "End of 3rd Grade" ) )

text( 1.1, T2, "Treatment Group", col="Steelblue", pos=4, cex=1.5 )
text( 1.1, C2, "Comparison Group", col="darkred", pos=4, cex=1.5 )
```




```{r}
set.seed(69)
male <- sample( c(0,1), 31000, T )
years <- rep( 0:30, each=1000 )
wages <- 8000 + 4000*male + 1000*years + 200*years*male + rnorm(1000,0,5000)
wages <- rescale(wages, to = c(17000, 56000))

dat <- data.frame( wages, male, years, stringsAsFactors=F )
head( dat, 10 ) %>% pander()
```


```{r}
dat.n <- sample_n( dat, 1000 ) # create a dataset for plotting  

plot( dat.n$years, dat.n$wages, pch=19, col=gray(0.5,0.1), cex=2.5, bty="n",
      main="Economic Returns on Experience",
      xlab="Years of Professional Experience", ylab="Wages" )
abline( lm(wages~years), col="darkred", lwd=3 )

text( 8, 50000, expression(Wages == b[0] + b[1] %.% Experience), col="darkred", cex=1.5 )
```



```{r}
palette( c("darkorange3","steelblue") )
plot( dat.n$years, dat.n$wages, pch=19, col=(dat.n$male+1), cex=1.2, bty="n", 
      main="Economic Returns on Experience", 
      xlab="Years of Professional Experience" )
abline( lm(wages~years), col="white", lwd=6 )

text( 8, 50000, "Wages = b0 + b1*Experience", col="gray10", cex=1.2 )

points( 20, 25000, col="steelblue", pch=19, cex=2 )
text( 20, 25000, "Wages of Men in the Sample", col="steelblue", pos=4 )
points( 20, 22000, col="darkorange3", pch=19, cex=2 )
text( 20, 22000, "Wages of Women in the Sample", col="darkorange3", pos=4 )
```



```{r}
dat.10 <- filter( dat, years %in% c(0,10) ) # select year=0 and year=10
dat.10$year10 <- ifelse( dat.10$years == 10, 1, 0 )
sample_n( dat.10, 10 ) %>% pander( row.names=F )
```


```{r}
reg2 <- lm( wages ~ male + year10 + male*year10, data=dat.10)

stargazer( reg2, type="text", digits=0,
           intercept.bottom = FALSE,
           covariate.labels=c("Constant (b0)", 
                              "male (b1)", 
                              "year10 (b2)", 
                              "male:year10 (b3)" ),
           omit.stat = c("ser","f","rsq","adj.rsq") )
```



```{r}
dat.sample <- sample_n( dat.10, 200 )
palette( c( adjustcolor( "steelblue", alpha.f=0.2), 
            adjustcolor( "darkorange3", alpha.f=0.2)  ) )

plot( dat$years, dat$wages, bty="n", type="n", xlim=c(-3,15),
      xlab="", ylab="Wages", xaxt="n",  
      main="Difference-in-Difference Model", cex.main=2 )

dat.male <- filter( dat.sample, male==1 )
points( dat.male$years+0.5+rnorm(nrow(dat.male ),0,0.03), 
        dat.male$wages,
        col=1, pch=19, cex=2 )

dat.female <- filter( dat.sample, male==0 )
points( dat.female$years-0.5 + rnorm(nrow(dat.female),0,0.03), dat.female$wages,
        col=2, pch=19, cex=2 )

axis( side=1, at=c(0,10), c("Time=0","Time=10") )

points( 0-0.5, coefficients(reg2)[1], 
        col="darkorange3", pch=19, cex=4 )
text( 0-0.5, coefficients(reg2)[1], 
      expression(b[0]), 
      pos=2, offset=1.5, col="darkorange3", cex=1.5 )

points( 0+0.5, coefficients(reg2)[1]+coefficients(reg2)[2], 
        col = "steelblue", pch = 19, cex = 4 )
text( 0+0.5, coefficients(reg2)[1]+coefficients(reg2)[2], 
      expression(b[0] + b[1]), 
      pos=4, col="steelblue", cex=1.5, offset=1.2 )

points( 10-0.5, coefficients(reg2)[1]+coefficients(reg2)[3], 
       col = "darkorange3", pch = 19, cex = 4 )
text( 10-0.5, coefficients(reg2)[1]+coefficients(reg2)[3], 
      expression(b[0] + b[2]), 
      pos=2, col="darkorange3", cex=1.5, offset=1.5 )

points( 10+0.5, sum( coefficients( reg2 )), 
        col = "steelblue", pch = 19, cex = 4 )
text( 10+0.5, sum( coefficients( reg2 )), 
      expression(b[0] + b[1] + b[2] + b[3]), 
      pos=4, col="steelblue", cex=1.5, offset=1.3 )

text( -0.5, 40000, "Female Wages", col="darkorange3", pos=4, offset=1, cex=1.3 )
points( -0.5, 40000, col="darkorange3", pch=19, cex=2 )

points( -0.5, 43000, col="steelblue", pch=19, cex=2 )
text( -0.5, 43000, "Male Wages", col="steelblue", pos=4, offset=1, cex=1.3 )

text( -0.5, 47000, 
      expression(Wages == b[0] + b[1]*Male + b[2]*Year[t==10] + b[3]*Male %.% Year[t==10]), 
      cex=1.3, col="gray60", pos=4, offset=0 )
```

